/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransaccionesRouteImport } from './routes/transacciones'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as RecurrentesRouteImport } from './routes/recurrentes'
import { Route as PresupuestoRouteImport } from './routes/presupuesto'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CuentasRouteImport } from './routes/cuentas'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AnalisisRouteImport } from './routes/analisis'
import { Route as IndexRouteImport } from './routes/index'

const TransaccionesRoute = TransaccionesRouteImport.update({
  id: '/transacciones',
  path: '/transacciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurrentesRoute = RecurrentesRouteImport.update({
  id: '/recurrentes',
  path: '/recurrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestoRoute = PresupuestoRouteImport.update({
  id: '/presupuesto',
  path: '/presupuesto',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentasRoute = CuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisRoute = AnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/calendario': typeof CalendarioRoute
  '/categorias': typeof CategoriasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cuentas': typeof CuentasRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/presupuesto': typeof PresupuestoRoute
  '/recurrentes': typeof RecurrentesRoute
  '/reportes': typeof ReportesRoute
  '/transacciones': typeof TransaccionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/calendario': typeof CalendarioRoute
  '/categorias': typeof CategoriasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cuentas': typeof CuentasRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/presupuesto': typeof PresupuestoRoute
  '/recurrentes': typeof RecurrentesRoute
  '/reportes': typeof ReportesRoute
  '/transacciones': typeof TransaccionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/calendario': typeof CalendarioRoute
  '/categorias': typeof CategoriasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cuentas': typeof CuentasRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/presupuesto': typeof PresupuestoRoute
  '/recurrentes': typeof RecurrentesRoute
  '/reportes': typeof ReportesRoute
  '/transacciones': typeof TransaccionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisis'
    | '/calendario'
    | '/categorias'
    | '/configuracion'
    | '/cuentas'
    | '/login'
    | '/metas'
    | '/presupuesto'
    | '/recurrentes'
    | '/reportes'
    | '/transacciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analisis'
    | '/calendario'
    | '/categorias'
    | '/configuracion'
    | '/cuentas'
    | '/login'
    | '/metas'
    | '/presupuesto'
    | '/recurrentes'
    | '/reportes'
    | '/transacciones'
  id:
    | '__root__'
    | '/'
    | '/analisis'
    | '/calendario'
    | '/categorias'
    | '/configuracion'
    | '/cuentas'
    | '/login'
    | '/metas'
    | '/presupuesto'
    | '/recurrentes'
    | '/reportes'
    | '/transacciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisisRoute: typeof AnalisisRoute
  CalendarioRoute: typeof CalendarioRoute
  CategoriasRoute: typeof CategoriasRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  CuentasRoute: typeof CuentasRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  PresupuestoRoute: typeof PresupuestoRoute
  RecurrentesRoute: typeof RecurrentesRoute
  ReportesRoute: typeof ReportesRoute
  TransaccionesRoute: typeof TransaccionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transacciones': {
      id: '/transacciones'
      path: '/transacciones'
      fullPath: '/transacciones'
      preLoaderRoute: typeof TransaccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurrentes': {
      id: '/recurrentes'
      path: '/recurrentes'
      fullPath: '/recurrentes'
      preLoaderRoute: typeof RecurrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuesto': {
      id: '/presupuesto'
      path: '/presupuesto'
      fullPath: '/presupuesto'
      preLoaderRoute: typeof PresupuestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuentas': {
      id: '/cuentas'
      path: '/cuentas'
      fullPath: '/cuentas'
      preLoaderRoute: typeof CuentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis': {
      id: '/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AnalisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisisRoute: AnalisisRoute,
  CalendarioRoute: CalendarioRoute,
  CategoriasRoute: CategoriasRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  CuentasRoute: CuentasRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  PresupuestoRoute: PresupuestoRoute,
  RecurrentesRoute: RecurrentesRoute,
  ReportesRoute: ReportesRoute,
  TransaccionesRoute: TransaccionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
